version: "3.7"
services:
  exporter:
    build: .
    container_name: exporter
    restart: always
    command:
      - "--redis-host=redis"
      - "--statsd-host=statsd"
      - "--collect-interval=2"
    depends_on:
      - redis
  redis:
    image: redis:5.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    volumes:
      - redis-data:/data
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: "host.docker.internal"
  statsd:
    image: statsd/statsd
    container_name: statsd
    ports:
      - 8125:8125/udp
    restart: always
    volumes:
      - ./hack/config.js:/usr/src/app/config.js

volumes:
  redis-data: